### ISSUE TITLE
Incomplete Poems bug

### ISSUE THREAD

**Issue by blairdrummond** [blairdrummond/NLP-Poetry#1]
poem.14631.txt is cutoff early. It's possible that more poems are having the same problem. This needs to be invesitgated

**Comment by blairdrummond** [comment]
Hey Bryan, Just want to confirm, I noticed that a few thousand poems were missing in your corpus since I last copied from it (Those files are now live in the corpus). I just want to confirm that those are the poems minus the truncated files? I saw a script there that seemed to indicate that. 
Cheers,
Blair

**Comment by bryanpaget** [comment]
I removed poems that were duplicates or just had too many weird characters from the original corpus on a few occasions, so your assumption may be true.  I am not sure how to confirm that, however... I wish there was a fast way to check.

Bryan

**Comment by blairdrummond** [comment]
Shoot. They aren't gone, but even worse, we don't have alternate copies of some of them.

Using the below code I tracked down a few examples, [poem.236302.txt](http://www.poetryfoundation.org/poetrymagazine/poem/183257)  for instance, gets cut off. So this suggests that we need to tweak our extraction tools and regather data.


*****************
```python
 import os
 inpath = 'corpus'
 for poem in os.listdir(inpath):
     with open(os.path.join(inpath,poem),'r') as f:
          read = f.read()
     if not read.rstrip(' \n ')[-1] in ['.','!','?','"']:
          print poem, read.rstrip(' \n ')[-1] 
```

**Comment by bryanpaget** [comment]
Blair,

I'm very sorry!  I guess the modifications I made to sopaHermosa need fixing.  My main effort was to get the script to run and not crash, which is what it kept doing.  I see another version of the script is in order.  Do you think that we should meet tomorrow to talk about this?

Bryan

**Comment by blairdrummond** [comment]
Fixed.
